### ISSUE TITLE
Playbooks: page crash after running a playbook

### ISSUE THREAD

**Issue by adityathebe** [flanksource/flanksource-ui#1626]
https://github.com/flanksource/flanksource-ui/assets/13419481/66ccdd33-4858-4c4e-a1a9-800d5a875a23

```
react-dom.production.min.js:189 TypeError: Cannot destructure property 'basename' of 'l.useContext(...)' as it is null.
    at index.js:707:1
    at ak (react-dom.production.min.js:167:135)
    at ui (react-dom.production.min.js:193:55)
    at i (react-dom.production.min.js:294:204)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oE (react-dom.production.min.js:271:86)
    at ox (react-dom.production.min.js:268:399)
    at x (scheduler.production.min.js:13:197)
a9 @ react-dom.production.min.js:189
a.componentDidCatch.t.callback @ react-dom.production.min.js:190
lW @ react-dom.production.min.js:144
uX @ react-dom.production.min.js:261
e @ react-dom.production.min.js:260
(anonymous) @ react-dom.production.min.js:260
oU @ react-dom.production.min.js:283
ox @ react-dom.production.min.js:269
x @ scheduler.production.min.js:13
T @ scheduler.production.min.js:14
Show 10 more frames
Show less
```

**Comment by mainawycliffe** [comment]
@adityathebe I think this should be fixed now, can you please confirm.

**Comment by adityathebe** [comment]
haven't noticed this again 👍
